import boto3
from botocore.exceptions import ClientError
import os
from dotenv import load_dotenv

load_dotenv()

# AWS SES client
ses_client = boto3.client(
    'ses',
    region_name=os.getenv('AWS_SES_REGION', 'us-east-1'),
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY')
)

YOUMATTER_EMAIL = os.getenv('YOUMATTER_EMAIL')


def send_guardian_alert(guardian_email: str, user_name: str, urgent: bool = False):
    """
    Sends email to guardian when crisis is detected.
    Vague for crisis, urgent for severe.
    """
    if urgent:
        subject = f"URGENT — {user_name} may need immediate help"
        body = f"""
Hello,

This is an urgent message from YouMatter, an AI mental health companion.

We are concerned that {user_name} may be in immediate danger right now.

Please reach out to them immediately or call emergency services (112) if needed.

— YouMatter Safety Team
        """
    else:
        subject = f"Checking in on {user_name}"
        body = f"""
Hello,

This is a gentle message from YouMatter, an AI mental health companion.

{user_name} might need your support today.
Please check in on them when you get a chance — a simple message or call can mean the world.

— YouMatter Team
        """

    try:
        response = ses_client.send_email(
            Source=YOUMATTER_EMAIL,
            Destination={
                'ToAddresses': [guardian_email]
            },
            Message={
                'Subject': {
                    'Data': subject,
                    'Charset': 'UTF-8'
                },
                'Body': {
                    'Text': {
                        'Data': body,
                        'Charset': 'UTF-8'
                    }
                }
            }
        )
        print(f"Email sent to {guardian_email}: {response['MessageId']}")
        return True
    except ClientError as e:
        print(f"Email failed: {e.response['Error']['Message']}")
        return False


def send_helpline_alert(user_name: str):
    """
    Sends alert to helpline email for severe crisis.
    """
    try:
        response = ses_client.send_email(
            Source=YOUMATTER_EMAIL,
            Destination={
                'ToAddresses': [YOUMATTER_EMAIL]  # Send to ourselves for now
            },
            Message={
                'Subject': {
                    'Data': f"SEVERE CRISIS ALERT — {user_name}",
                    'Charset': 'UTF-8'
                },
                'Body': {
                    'Text': {
                        'Data': f"""
SEVERE CRISIS DETECTED

User {user_name} has shown signs of immediate danger.

This alert was automatically generated by YouMatter AI Safety System.

Please follow up immediately.

— YouMatter Safety System
                        """,
                        'Charset': 'UTF-8'
                    }
                }
            }
        )
        print(f"Helpline alert sent: {response['MessageId']}")
        return True
    except ClientError as e:
        print(f"Helpline alert failed: {e.response['Error']['Message']}")
        return False


# Test
if __name__ == "__main__":
    result = send_guardian_alert(
        guardian_email="your_test_email@gmail.com",
        user_name="Test User",
        urgent=False
    )
    print(f"Email sent: {result}")