import os
import smtplib
import logging
from email.mime.text import MIMEText
# pyrefly: ignore [missing-import]
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("youmatter.email")

# SMTP config — works with Gmail (using an App Password, not your normal
# password) or any other email provider that offers SMTP access.
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME")  # your sending email address
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")  # app password, not your login password
YOUMATTER_EMAIL = os.getenv("YOUMATTER_EMAIL", SMTP_USERNAME)


def _send_email(to_email: str, subject: str, body: str) -> bool:
    """Sends a plain-text email over SMTP. Returns True on success."""
    if not to_email:
        logger.warning("_send_email: no recipient provided, skipping send")
        return False
    if not SMTP_USERNAME or not SMTP_PASSWORD:
        logger.error("_send_email: SMTP_USERNAME/SMTP_PASSWORD not configured")
        return False

    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = YOUMATTER_EMAIL
    msg["To"] = to_email

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(YOUMATTER_EMAIL, [to_email], msg.as_string())
        logger.info(f"Email sent to {to_email}")
        return True
    except Exception as e:
        logger.error(f"Email send failed to {to_email}: {e}", exc_info=True)
        return False


def send_guardian_alert(guardian_email, user_name: str, urgent: bool = False) -> bool:
    """
    Sends email to guardian when crisis is detected.
    Vague for crisis, urgent for severe.
    """
    if isinstance(guardian_email, list):
        to_email = guardian_email[0] if guardian_email else None
    else:
        to_email = guardian_email

    if urgent:
        subject = f"URGENT — {user_name} may need immediate help"
        body = f"""Hello,

This is an urgent message from YouMatter, an AI mental health companion.

We are concerned that {user_name} may be in immediate danger right now.

Please reach out to them immediately or call emergency services (112) if needed.

— YouMatter Safety Team
"""
    else:
        subject = f"Checking in on {user_name}"
        body = f"""Hello,

This is a gentle message from YouMatter, an AI mental health companion.

{user_name} might need your support today.
Please check in on them when you get a chance — a simple message or call can mean the world.

— YouMatter Team
"""

    return _send_email(to_email, subject, body)


def send_helpline_alert(user_name: str) -> bool:
    """
    Sends alert to YouMatter's own inbox for severe crisis, so the team
    (or you, during dev/testing) sees it and can follow up.
    """
    subject = f"SEVERE CRISIS ALERT — {user_name}"
    body = f"""SEVERE CRISIS DETECTED

User {user_name} has shown signs of immediate danger.

This alert was automatically generated by YouMatter AI Safety System.

Please follow up immediately.

— YouMatter Safety System
"""
    return _send_email(YOUMATTER_EMAIL, subject, body)


# Test — set TEST_GUARDIAN_EMAIL in your .env before running this file directly
if __name__ == "__main__":
    test_email = os.getenv("TEST_GUARDIAN_EMAIL")
    if not test_email:
        print("Set TEST_GUARDIAN_EMAIL in your .env to test this file directly.")
    else:
        result = send_guardian_alert(
            guardian_email=test_email,
            user_name="Test User",
            urgent=False
        )
        print(f"Email sent: {result}")